### ISSUE TITLE
no result video output

### ISSUE THREAD

**Issue by samiuns** [ajinkyatalekar/RedditTTS#4]
Progress will be logged here.
Logging in Reddit...
Logged in successfully!
Checking if subreddit exists...
Subreddit Exists! Fetching posts...
Generating images...
Successfully generated images!
Generating audio...
Generating video...
Done! see 'out/' folder for the final video.

**Comment by ajinkyatalekar** [comment]
This happens when all the posts being processed are NSFW. Try increasing the number of posts and that should work.

**Comment by ajinkyatalekar** [comment]
Hello! Could you check out the updated version I have put up on main and see if you are able to get it to work? I've added a bunch of new features, but I have more to do.

Now the post being NSFW does not matter, also you can choose what post and comments you want to make a video of.
